# Generated by Django 4.2.1 on 2023-05-17 19:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photosProfil/')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('date_affectation', models.DateField(default=datetime.date.today, null=True)),
                ('profil_linkedin_ou_site_personnel', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetRealisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('photoPrj', models.FileField(blank=True, null=True, upload_to='photoProjet/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Charte graphique ', 'Charte graphique '), ('Objet  3D ', 'Objet  3D '), ('Scénarisation', 'Scénarisation')], default='Charte graphique ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Charte graphique ', 'Charte graphique '), ('Objet  3D ', 'Objet  3D '), ('Scénarisation', 'Scénarisation')], default='Charte graphique ', max_length=50)),
                ('projet', models.ManyToManyField(related_name='projets', to='artyprod.projetrealisee')),
            ],
        ),
        migrations.AddField(
            model_name='projetrealisee',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artyprod.service'),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('FichierProjet', models.FileField(blank=True, null=True, upload_to='FichierProjet/')),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artyprod.equipe')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artyprod.service')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(related_name='equipes', to='artyprod.personnel'),
        ),
    ]
