# Generated by Django 4.2.1 on 2023-05-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='realise',
            field=models.BooleanField(default=False),
        ),
    ]
