# Generated by Django 4.2.1 on 2023-05-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0003_projet_realise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artyprod.projet')),
            ],
        ),
    ]
