# Generated by Django 4.2.1 on 2023-05-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='photoPrj',
            field=models.FileField(blank=True, null=True, upload_to='photoProjet/'),
        ),
    ]
