# Generated by Django 4.2.1 on 2023-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0006_alter_portfolio_photoprj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photoPrj',
            field=models.ImageField(blank=True, null=True, upload_to='FichierProjet/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='FichierProjet',
            field=models.ImageField(blank=True, null=True, upload_to='FichierProjet/'),
        ),
        migrations.AlterField(
            model_name='projetrealisee',
            name='photoPrj',
            field=models.ImageField(blank=True, null=True, upload_to='FichierProjet/'),
        ),
    ]
