# Generated by Django 4.2.1 on 2023-05-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0007_alter_portfolio_photoprj_alter_projet_fichierprojet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='photoPrj',
            new_name='FichierProjet',
        ),
        migrations.RenameField(
            model_name='projetrealisee',
            old_name='photoPrj',
            new_name='FichierProjet',
        ),
    ]
