# Generated by Django 4.2.1 on 2023-05-22 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artyprod', '0008_rename_photoprj_portfolio_fichierprojet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, null=True),        ),
    ]
