# Generated by Django 4.2.1 on 2023-05-22 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artyprod', '0010_alter_projet_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('fichier_projet', models.FileField(upload_to='FichierProjet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetAccepte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('fichier_projet', models.FileField(upload_to='FichierProjet')),
                ('demande_projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artyprod.demandeprojet')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='projet_accepte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artyprod.projetaccepte'),
        ),
    ]
