# Generated by Django 4.2.1 on 2023-05-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0011_demandeprojet_projetaccepte_projet_projet_accepte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeprojet',
            name='fichier_projet',
        ),
        migrations.RemoveField(
            model_name='projetaccepte',
            name='fichier_projet',
        ),
        migrations.AddField(
            model_name='demandeprojet',
            name='FichierProjet',
            field=models.FileField(blank=True, null=True, upload_to='FichierProjet/'),
        ),
        migrations.AddField(
            model_name='projetaccepte',
            name='FichierProjet',
            field=models.FileField(blank=True, null=True, upload_to='FichierProjet'),
        ),
    ]
