# Generated by Django 4.2.1 on 2023-05-23 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artyprod', '0012_remove_demandeprojet_fichier_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets_demandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
